#include "awtk.h"
#include "base/assets_manager.h"
#ifndef WITH_FS_RES
#include "default/inc/strings/zh_CN.data"
#include "default/inc/strings/en_US.data"
#include "default/inc/styles/main.data"
#include "default/inc/styles/keyboard.data"
#include "default/inc/styles/layer_window.data"
#include "default/inc/styles/default.data"
#include "default/inc/ui/kb_ascii.data"
#include "default/inc/ui/kb_phone.data"
#include "default/inc/ui/main.data"
#include "default/inc/ui/kb_int.data"
#include "default/inc/ui/kb_hex.data"
#include "default/inc/ui/kb_float.data"
#include "default/inc/ui/layer_window.data"
#include "default/inc/ui/kb_ufloat.data"
#include "default/inc/ui/kb_default.data"
#include "default/inc/ui/kb_uint.data"
#ifdef WITH_STB_IMAGE
#include "default/inc/images/radio_unchecked_d.res"
#include "default/inc/images/arrow_up_n.res"
#include "default/inc/images/arrow_right_p.res"
#include "default/inc/images/arrow_right_f.res"
#include "default/inc/images/arrow_up_o.res"
#include "default/inc/images/arrow_left_o.res"
#include "default/inc/images/arrow_right_d.res"
#include "default/inc/images/arrow_left_n.res"
#include "default/inc/images/check_checked_d.res"
#include "default/inc/images/radio_checked.res"
#include "default/inc/images/check_unchecked_d.res"
#include "default/inc/images/radio_checked_d.res"
#include "default/inc/images/arrow_down_n.res"
#include "default/inc/images/arrow_down_o.res"
#include "default/inc/images/arrow_down_d.res"
#include "default/inc/images/arrow_down_p.res"
#include "default/inc/images/arrow_down_f.res"
#include "default/inc/images/radio_unchecked.res"
#include "default/inc/images/check_unchecked.res"
#include "default/inc/images/arrow_up_p.res"
#include "default/inc/images/arrow_right_n.res"
#include "default/inc/images/arrow_right_o.res"
#include "default/inc/images/arrow_up_f.res"
#include "default/inc/images/arrow_left_d.res"
#include "default/inc/images/arrow_left_f.res"
#include "default/inc/images/arrow_up_d.res"
#include "default/inc/images/arrow_left_p.res"
#include "default/inc/images/check_checked.res"
#else
#endif /*WITH_STB_IMAGE*/
#ifdef WITH_VGCANVAS
#endif /*WITH_VGCANVAS*/
#ifdef WITH_TRUETYPE_FONT
#include "default/inc/fonts/default.res"
#else /*WITH_TRUETYPE_FONT*/
#endif /*WITH_TRUETYPE_FONT*/
#endif /*WITH_FS_RES*/

ret_t assets_init_default(void) {
  assets_manager_t* am = assets_manager();
  assets_manager_set_theme(am, "default");

#ifdef WITH_FS_RES
  assets_manager_preload(am, ASSET_TYPE_FONT, "default");
  assets_manager_preload(am, ASSET_TYPE_STYLE, "default");
#else
  assets_manager_add(am, strings_zh_CN);
  assets_manager_add(am, strings_en_US);
  assets_manager_add(am, style_main);
  assets_manager_add(am, style_keyboard);
  assets_manager_add(am, style_layer_window);
  assets_manager_add(am, style_default);
  assets_manager_add(am, ui_kb_ascii);
  assets_manager_add(am, ui_kb_phone);
  assets_manager_add(am, ui_main);
  assets_manager_add(am, ui_kb_int);
  assets_manager_add(am, ui_kb_hex);
  assets_manager_add(am, ui_kb_float);
  assets_manager_add(am, ui_layer_window);
  assets_manager_add(am, ui_kb_ufloat);
  assets_manager_add(am, ui_kb_default);
  assets_manager_add(am, ui_kb_uint);
  assets_manager_add(am, image_radio_unchecked_d);
  assets_manager_add(am, image_arrow_up_n);
  assets_manager_add(am, image_arrow_right_p);
  assets_manager_add(am, image_arrow_right_f);
  assets_manager_add(am, image_arrow_up_o);
  assets_manager_add(am, image_arrow_left_o);
  assets_manager_add(am, image_arrow_right_d);
  assets_manager_add(am, image_arrow_left_n);
  assets_manager_add(am, image_check_checked_d);
  assets_manager_add(am, image_radio_checked);
  assets_manager_add(am, image_check_unchecked_d);
  assets_manager_add(am, image_radio_checked_d);
  assets_manager_add(am, image_arrow_down_n);
  assets_manager_add(am, image_arrow_down_o);
  assets_manager_add(am, image_arrow_down_d);
  assets_manager_add(am, image_arrow_down_p);
  assets_manager_add(am, image_arrow_down_f);
  assets_manager_add(am, image_radio_unchecked);
  assets_manager_add(am, image_check_unchecked);
  assets_manager_add(am, image_arrow_up_p);
  assets_manager_add(am, image_arrow_right_n);
  assets_manager_add(am, image_arrow_right_o);
  assets_manager_add(am, image_arrow_up_f);
  assets_manager_add(am, image_arrow_left_d);
  assets_manager_add(am, image_arrow_left_f);
  assets_manager_add(am, image_arrow_up_d);
  assets_manager_add(am, image_arrow_left_p);
  assets_manager_add(am, image_check_checked);
#ifdef WITH_VGCANVAS
#endif /*WITH_VGCANVAS*/
#ifdef WITH_TRUETYPE_FONT
  assets_manager_add(am, font_default);
#else /*WITH_TRUETYPE_FONT*/
#endif /*WITH_TRUETYPE_FONT*/
#endif

  tk_init_assets();
  return RET_OK;
}
